// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBphuNlMBK2rhRsXLo1x8J7KT0tz8jYP5k',
    appId: '1:101216335639:web:ae307ef37af61036dca952',
    messagingSenderId: '101216335639',
    projectId: 'capygram-aae3d',
    authDomain: 'capygram-aae3d.firebaseapp.com',
    storageBucket: 'capygram-aae3d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-QimDB362aDLkP6lA-3s4KfOw5AFBdpM',
    appId: '1:101216335639:android:4d7b27c1c8caaadadca952',
    messagingSenderId: '101216335639',
    projectId: 'capygram-aae3d',
    storageBucket: 'capygram-aae3d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr76c6sLc6i28ZBEN6Tlp1oS-hkiAegqw',
    appId: '1:101216335639:ios:9d9cdc688595e6ecdca952',
    messagingSenderId: '101216335639',
    projectId: 'capygram-aae3d',
    storageBucket: 'capygram-aae3d.appspot.com',
    iosClientId: '101216335639-shbs124alo89u7v602bm8onncd2n4ktt.apps.googleusercontent.com',
    iosBundleId: 'com.example.capygram',
  );
}
